import { BookMeta } from './types';

export const KITAPLAR: BookMeta[] = [
  {
    slug: 'bukhari',
    file: 'bukhari_tr.json',
    turkishName: 'Buhârî',
    arabicName: 'صحيح البخاري',
    from: '#1B4332',
    to: '#2D6A4F',
    totalHadiths: 7589,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'muslim',
    file: 'muslim_ar.json',
    turkishName: 'Müslim',
    arabicName: 'صحيح مسلم',
    from: '#880E4F',
    to: '#AD1457',
    totalHadiths: 7453,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'tirmizi',
    file: 'tirmizi_ar.json',
    turkishName: 'Tirmizî',
    arabicName: 'سنن الترمذي',
    from: '#6B1A1A',
    to: '#9B3A3A',
    totalHadiths: 3956,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'ebudavud',
    file: 'abudawud_ar.json',
    turkishName: 'Ebû Dâvûd',
    arabicName: 'سنن أبي داود',
    from: '#7A5C00',
    to: '#B8860B',
    totalHadiths: 5274,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'ibnmace',
    file: 'ibnmace_ar.json',
    turkishName: 'İbn Mâce',
    arabicName: 'سنن ابن ماجه',
    from: '#4A1A6B',
    to: '#7B3FA0',
    totalHadiths: 4341,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'nesai',
    file: 'nesai_ar.json',
    turkishName: 'Nesâî',
    arabicName: 'سنن النسائي',
    from: '#0F4D4D',
    to: '#1A7A7A',
    totalHadiths: 5758,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'darimi',
    file: 'darimi_ar.json',
    turkishName: 'Dârimî',
    arabicName: 'سنن الدارمي',
    from: '#1A3A5C',
    to: '#2E6DA4',
    totalHadiths: 3406,
    translationPending: true,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'ahmed',
    file: 'ahmed_ar.json',
    turkishName: 'Müsned-i Ahmed',
    arabicName: 'مسند أحمد',
    from: '#3B1A00',
    to: '#8B4513',
    totalHadiths: 1374,
    translationPending: true,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'malik',
    file: 'malik_ar.json',
    turkishName: 'Muvatta',
    arabicName: 'موطأ مالك',
    from: '#1A1A3B',
    to: '#4A4A8B',
    totalHadiths: 1985,
    translationPending: true,
    kategori: 'kutubu-tisa',
  },
  {
    slug: 'mishkat',
    file: 'mishkat_ar.json',
    turkishName: 'Mişkâtü\'l-Mesâbîh',
    arabicName: 'مشكاة المصابيح',
    from: '#1A1A00',
    to: '#6B6B00',
    totalHadiths: 4428,
    translationPending: true,
    kategori: 'secme-eserler',
  },
  {
    slug: 'edeblmufrad',
    file: 'edeblmufrad_ar.json',
    turkishName: 'el-Edebü\'l-Müfred',
    arabicName: 'الأدب المفرد',
    from: '#3B2200',
    to: '#C47A00',
    totalHadiths: 1326,
    translationPending: true,
    kategori: 'secme-eserler',
  },
  {
    slug: 'riyazussalihin',
    file: 'riyazussalihin_ar.json',
    turkishName: 'Riyâzü\'s-Sâlihîn',
    arabicName: 'رياض الصالحين',
    from: '#6B1530',
    to: '#B5294E',
    totalHadiths: 1896,
    translationPending: true,
    kategori: 'secme-eserler',
  },
];

export function getKitap(slug: string): BookMeta | undefined {
  return KITAPLAR.find((k) => k.slug === slug);
}
